import Navbar from "@/components/Navbar";
import { ReduxProvider } from "@/components/ReduxProvider";
import type { Metadata } from "next";
import { Rubik } from "next/font/google";


export const metadata: Metadata = {
  title: "Fresh Harvests",
  description: "Generated by create next app",
};

const rubik = Rubik({
  variable: "--font-rubik-sans",
  subsets: ["latin"],
  display: "swap", // Optional but recommended for performance
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <main className={`${rubik.variable} font-sans`}>
    <ReduxProvider>
  <Navbar></Navbar>

    <div >
  {children}
    </div>

    </ReduxProvider>
  
      
</main>
  );
}
