import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";

const rubik = Rubik({
  variable:"--font-rubik-sans",
  subsets:["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth scroll-mt-44"  >
      <body
        className={`${rubik.variable}  antialiased bg-white `}
      >
        {children}
      </body>
    </html>
  );
}
